# Generated by Django 4.1.4 on 2022-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capteur',
            old_name='value',
            new_name='humidite',
        ),
        migrations.RemoveField(
            model_name='capteur',
            name='keyname',
        ),
        migrations.AddField(
            model_name='capteur',
            name='pression',
            field=models.CharField(default=2022, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capteur',
            name='temperature',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
