# Generated by Django 4.1.4 on 2022-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_value_capteur_humidite_remove_capteur_keyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='humidite',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='pression',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='temperature',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
