# Generated by Django 4.1.4 on 2022-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_capteur_humidite_alter_capteur_pression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
